### ISSUE TITLE
Crashes when not using latest Xcode (7.3 beta)

### ISSUE THREAD

**Issue by DeepAnchor** [davidlawson/SimulatorController#1]
Hey, thanks so much for making this! It helped me a lot in figuring out how exactly to use the FBSimulatorControl API.

Just wanted to note that running it from the binary release crashes immediately when trying to launch non-system apps. Tracked it down to the `launchApplication` call (line #140 in SimulatorController.swift). The same thing happens when building it from Xcode 7.2 (after reverting `button.action = #selector(toggledSimulator)` back to the old selector syntax).

Everything works fine when building and running from Xcode 7.3. Perhaps a warning should be added to the readme?

**Comment by davidlawson** [comment]
Thanks for trying it out!

I'm able to launch non-system applications with both the binary release and after building with Xcode 7.2.1 (after a `xcode-select` and `carthage bootstrap`). I'm running OS X 10.11.3.

Strange how your crash doesn't happen after building and running from Xcode 7.3, given that the binary release is compiled with that version of Xcode. Does your crash happen with the iPhone 4s as well as iPhone 6?

I should probably look into getting rid of the `try!` calls and showing error messages in a `NSAlert`.

**Comment by davidlawson** [comment]
I've added some basic error handling to the latest release, hopefully the error messages will provide some insight.

**Comment by DeepAnchor** [comment]
Hmm, strange. Not sure what I changed, but it's no longer working again on either 7.2 or 7.3!
It fails with the following error output (in console since it didn't fit inside the error modal):

```
2016-03-10 16:58:05.928 SimulatorController[61525:1112868] launchctl print returned an error code: 32767
error = Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed to launch application App Launch na.ios-client (na.ios-client) | Arguments (
) | Environment {
} | StdOut (null) | StdErr (null)" UserInfo={NSLocalizedDescription=Failed to launch application App Launch na.ios-client (na.ios-client) | Arguments (
) | Environment {
} | StdOut (null) | StdErr (null), launchd_is_running=1, launchd_subprocesses=[Process CFNetworkAgent | PID 61975, Process com.apple.Safari.History | PID 61974, Process syncdefaultsd | PID 61973, Process bird | PID 61972, Process splashboardd | PID 61971, Process ondemandd | PID 61970, Process filecoordinationd | PID 61859, Process nanoregistrylaunchd | PID 61848, Process containermanagerd | PID 61847, Process ServerFileProvider | PID 61846, Process carkitd | PID 61845, Process searchd | PID 61839, Process akd | PID 61833, Process accountsd | PID 61832, Process nsurlstoraged | PID 61831, Process itunesstored | PID 61820, Process useractivityd | PID 61819, Process IMDPersistenceAgent | PID 61817, Process calaccessd | PID 61816, Process com.apple.audio.SystemSoundServer-iOS-Simulator | PID 61815, Process medialibraryd | PID 61814, Process passd | PID 61813, Process profiled | PID 61812, Process mobileassetd | PID 61801, Process com.apple.accessibility.AccessibilityUIServer | PID 61800, Process kbd | PID 61799, Process cplogd | PID 61788, Process pkd | PID 61787, Process nanoregistryd | PID 61786, Process tccd | PID 61785, Process geod | PID 61784, Process lsd | PID 61783, Process networkd | PID 61782, Process MobileGestaltHelper | PID 61781, Process callservicesd | PID 61780, Process securityd | PID 61779, Process apsd | PID 61778, Process distnoted | PID 61777, Process nsurlsessiond | PID 61776, Process cfprefsd | PID 61775, Process aslmanager | PID 61764, Process notifyd | PID 61763, Process CoreSimulatorBridge | PID 61762, Process configd_sim | PID 61761, Process SimulatorBridge | PID 61760, Process revisiond | PID 61759, Process assertiond | PID 61758, Process locationd | PID 61757, Process sharingd | PID 61756, Process backboardd | PID 61755, Process SpringBoard | PID 61754, Process wcd | PID 61753, Process assetsd | PID 61752, Process companionappd | PID 61751, Process AppleIDAuthAgent | PID 61750, Process touchsetupd | PID 61749, Process identityservicesd | PID 61748, Process installd | PID 61747, Process healthd | PID 61746, Process ids_simd | PID 61745, Process mediaremoted | PID 61744, Process mstreamd | PID 61743, Process routined | PID 61742, Process fileproviderd | PID 61741, Process UserEventAgent | PID 61740, Process syslogd | PID 61739], NSUnderlyingError=0x6080006421c0 {Error Domain=FBSOpenApplicationErrorDomain Code=1 "The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.)}}}

```

It looks like the error is not relevant to this project now though, so I'll just go ahead and close the issue. Will post with the solution for future reference if I solve it!

**Comment by DeepAnchor** [comment]
Ok, I was able to reproduce the issue again. The problem seems to depend on where I drag my built `.app` from -either from a `7.2` workspace or `7.3`. It doesn't even matter which workspace it was built in. For example, I got it to work with the following steps:

1.) compile my app on `7.2`
2.) start `SimulatorController` from the binary
3.) open my app on `7.3` (which doesn't even build, due to a seg fault in one of the dependencies)
4.) drag the `.app` from the 7.3 workspace into `SimulatorController`

I verified this with a dummy app also, which _does_ build on `7.3`. When I open the dummy app's workspace in `7.2`, build it, then drag it to `SimulatorController`, it crashes with the above error. However when I drag the same binary from a `7.3` workspace, it works.  

Very strange indeed, but I think this bug might be on the Xcode side of things, or maybe how the drag and drop is finding the path to the binary.

**Comment by davidlawson** [comment]
Strange! The relevant code would be:
https://github.com/davidlawson/SimulatorController/blob/master/SimulatorController/ViewController.swift#L53-L71
and
https://github.com/davidlawson/SimulatorController/blob/master/SimulatorController/SimulatorController.swift#L98-L112

**Comment by davidlawson** [comment]
@DeepAnchor I'm getting the same issue, though I still can't work out how to reliably reproduce it. Have you tried playing around with `xcode-select`, changing between the 7.2 and 7.3 simulators?

**Comment by DeepAnchor** [comment]
@davidlawson yeah I've tried building and running with different combinations of 7.2 / 7.3 with `xcode-select`, `xcrun` and `simctl` and everything works fine when I know exactly which build file I'm inputting into `SimulatorController`... let me explain.

I think what is happening is that Xcode 7.2 is not finding built files for simulator target devices by default. For example, building for the iOS Simulator iPhone 6s (9.2) target, the only .app that shows up in `products/` has this path -and this was probably a file I had built earlier for my actual physical device: 

`file:///Users/deepanchor/Library/Developer/Xcode/DerivedData/ios-client-fnmkxplipdtgyucvvzdbsgdoovzp/Build/Products/`**`Debug-iphoneos`**`/ios-client.app`

whereas .app in the `products/` folder in the 7.3 workspace _does_ find the simulator path, and points to:

`file:///Users/deepanchor/Library/Developer/Xcode/DerivedData/ios-client-fnmkxplipdtgyucvvzdbsgdoovzp/Build/Products/`**`Debug-iphonesimulator`**`/ios-client.app`

From what I gather, the `iphonesimulator` directory is for simulator-only x86 arch builds whereas the `iphoneos` directory is for the real ARM devices. When the simulator tries to read the build for a real device, it crashes. 

Xcode has a $(EFFECTIVE_PLATFORM_NAME) variable defined that's supposed to evaluate either to 'iphoneos' or 'iphonesimulator' based on the target device selected, changing the .app file that shows up under `products/`. When a simulator target device is selected, it's supposed to change $(EFFECTIVE_PLATFORM_NAME) to `iphonesimulator` and display the simulator build... but it doesn't! 

So, under the assumption that `products/` was displaying the correct .app for my target device, it seems I was unknowingly using the .app built for my physical device as input to `SimulatorController` which is what caused it to crash. 7.3 does correctly take the target device into account. Maybe we could add some kind of regex check to ensure that `appURL` is a valid simulator build path and throw an error if not?

**Comment by davidlawson** [comment]
@DeepAnchor good work on the debugging!!

FBSimulatorControl works out what architectures the chosen binary includes, so we could use that to detect a simulator build. 

We could also just detect `[target]-iphoneos` in the .app path and ask the user if they want to switch to `../[target]-iphonesimulator/[app]` (given that it exists).
